### PR TITLE
updating fastclick.min.js for Branch2

### PR DESCRIPTION
**Pull request by mb-smartcookie**
Can you check this?

### CODE REVIEW

**Comment by mb-smartcookie** [comment]
Yes, I am sure about this file

**Comment by mk-smartcookie** [comment]
I've looked at the upload on the shopify store and the amend is working well. Lets merge.

**Comment by mk-smartcookie** [comment]
@mb-smartcookie

**Comment by mb-smartcookie** [comment]
Fine, merging

**Pull request merged**
